### ISSUE TITLE
Add a loading icon to the lecture list page

### ISSUE THREAD

**Issue by amuamushu** [googleinterns/zoomtube#300]
Loading lectures takes a couple of seconds. Using a transaction would make it faster. Alternatively, we could add a loading icon to make it obvious to the user that the lectures have not loaded yet.

**Comment by n-wach** [comment]
Looked into this, and transactions don't really help here...  I do agree with the point on adding a loading icon, so am going to change the title of this issue to that.

**Comment by n-wach** [comment]
https://getbootstrap.com/docs/4.5/components/spinners/
