### ISSUE TITLE
Pin footer to the bottom of screen

### ISSUE THREAD

**Issue by jaysaleh** [googleinterns/zoomtube#346]
Currently the footer is not being pinned to the bottom of the screen.

**Comment by n-wach** [comment]
Oh, I was the one that removed this--sorry!  The reason was that on smaller screens, or with a lot of lectures, sometimes the content would overflow the screen and the footer would appear on top of stuff.

Something to check when fixing this

**Comment by jaysaleh** [comment]
> Oh, I was the one that removed this--sorry! The reason was that on smaller screens, or with a lot of lectures, sometimes the content would overflow the screen and the footer would appear on top of stuff.
> 
> Something to check when fixing this

Thanks for letting me know, I will look into it!
