### ISSUE TITLE
Add deployed website Url to Readme.md.

### ISSUE THREAD

**Issue by amuamushu** [googleinterns/zoomtube#74]
Url to add: https://zoomtube-step-2020.appspot.com/lecture-view.html?id=123

**Comment by n-wach** [comment]
We should add this to PR #75

**Comment by n-wach** [comment]
Or we can hold off until more is merged and we aren't linking to a random `id`.

**Comment by n-wach** [comment]
Added a link to `/`.  We need to add an index.html page or servlet to handle requests to this url, otherwise it 404s.  I'll add an issue.
