### ISSUE TITLE
Ensure that having a <p> in a method header paragraph doesn't cause formatting issues.

### ISSUE THREAD

**Issue by amuamushu** [googleinterns/zoomtube#99]
Having `<p>` in a method header paragraph may cause the paragraph to split at the `<p>` tag. We are not sure if this is an issue but would like to be aware of it.

This occurs in the transcript.js file.
```
/**
 * Creates a <p> tag to store the given {@code text} inside the
 * {@code container} and returns the <p> tag using the given text
 *
 * <p>The <p> tag is returned so that the calling method can add additional
 * attributes to the tag.
 */
function appendPTagToContainer(text, container) {
}
```

**Comment by n-wach** [comment]
Can we just do something like `creates a {@code p} tag`?

**Comment by n-wach** [comment]
With #222 this will no longer be an issue.
